### PR TITLE
Merge Void linux ANSI into main zeitfetch

### PR DESCRIPTION
**Pull request by nidnogg**
Heya @Xaidee! 
I noticed you put in a pretty good rendition of the void linux logo. Are you planning to merge it back in anytime soon?

Cheers!

### CODE REVIEW

**Comment by Xaidee** [comment]
Yes I was planning to eventually, maybe with some other distros too but the Void logo was ripped from neofetch and I wasn't sure you'd be okay with that

**Comment by nidnogg** [comment]
> Yes I was planning to eventually, maybe with some other distros too but the Void logo was ripped from neofetch and I wasn't sure you'd be okay with that. Just been experimenting with your code on my system in the mean time.

Yeah, so it's fine to include those from neofetch as long as they're credited under https://github.com/nidnogg/zeitfetch?tab=readme-ov-file#disclaimer-for-ascii-logos. (I believe a few came from there).

When you think it's ready, feel free to either ping me here or open another PR.

**Comment by Xaidee** [comment]
I was thinking, especially comparing this implementation to others, it'd be awesome if there was a public database of ASCI and ANSI art that fetch implementations and possibly other projects could pull from to remove the need for individual maintenance of including all operating systems individually

**Comment by Xaidee** [comment]
@nidnogg Sorry for the last messy commits, my code editor messed with README.md and had to fix that manually but this PR should be ready!

**Comment by Xaidee** [comment]
image

I did actually attempt at making an altered version of the original ASCII to make it more readable on black and white while also mimicking the style of the other logos currently in zeitfetch.
Let me know if you'd prefer this version over the neofetch rip and ill update my PR.

**Comment by nidnogg** [comment]
> image
> 
> I did actually attempt at making an altered version of the original ASCII to make it more readable on black and white while also mimicking the style of the other logos currently in zeitfetch. Let me know if you'd prefer this version over the neofetch rip and ill update my PR.
> 
> EDIT: I've since cleaned the design further after noticing mistakes in the above image

I like your version better! Let's add that one in.

**Pull request closed without merging**
